CREATE TABLE tb_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE tb_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE tb_profile_roles (
    profile_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT tb_profile_roles_pk PRIMARY KEY (profile_id, role_id),
    CONSTRAINT tb_profile_roles_role_fk FOREIGN KEY (role_id) REFERENCES tb_roles,
    CONSTRAINT tb_profile_roles_profile_fk FOREIGN KEY (profile_id) REFERENCES tb_profiles
);

CREATE TABLE tb_users_profiles (
    user_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    CONSTRAINT tb_users_profiles_pk PRIMARY KEY (user_id, profile_id),
    CONSTRAINT tb_users_profiles_user_fk FOREIGN KEY (user_id) REFERENCES tb_users,
    CONSTRAINT tb_users_profiles_profile_fk FOREIGN KEY (profile_id) REFERENCES tb_profiles
);

-- Step 1: Insert all distinct roles from users into tb_roles
INSERT INTO tb_roles (name) 
SELECT DISTINCT UNNEST(roles) as role_name
FROM tb_users
WHERE roles IS NOT NULL AND array_length(roles, 1) > 0
ON CONFLICT (name) DO NOTHING;

-- Step 2: Create a "Default" profile
INSERT INTO tb_profiles (name) VALUES ('Default') 
ON CONFLICT (name) DO NOTHING;

-- Step 3: Assign Default Profile to all users
INSERT INTO tb_users_profiles (user_id, profile_id)
SELECT 
    u.id, 
    (SELECT id FROM tb_profiles WHERE name = 'Default') as profile_id
FROM tb_users u
ON CONFLICT (user_id, profile_id) DO NOTHING;

-- Step 4: Add all roles to the Default profile
INSERT INTO tb_profile_roles (profile_id, role_id)
SELECT 
    p.id as profile_id,
    r.id as role_id
FROM tb_profiles p
CROSS JOIN tb_roles r
WHERE p.name = 'Default'
ON CONFLICT (profile_id, role_id) DO NOTHING;

ALTER TABLE tb_users
DROP COLUMN roles;