CREATE TABLE tb_users_reset_password_token (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encoded_password VARCHAR(255) NOT NULL,
    requestedAt      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    token            VARCHAR(255),
    used             BOOLEAN NOT NULL,
    user_id          BIGINT NOT NULL,

    CONSTRAINT tb_users_reset_password_token_user_fk FOREIGN KEY (user_id) REFERENCES tb_users
);