CREATE TABLE tb_users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(15) NOT NULL,
    name             VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    encoded_password VARCHAR(255) NOT NULL,
    roles            VARCHAR(255) ARRAY,
    deleted     BOOLEAN DEFAULT false,

    CONSTRAINT tb_users_email_UK    UNIQUE(email),
    CONSTRAINT tb_users_username_UK UNIQUE(username)
);

-- Usuário com apenas a role ADMIN
INSERT INTO tb_users (username, name, email, encoded_password, roles) VALUES ('admin', 'System Administrator', 'sysadmin@passport.vepo.dev', 'IwS3Mm4oGEfpwPDC3Vom20ViYgXhVCxHeBGr8aluY9tC9o668ghxJ2fMQQUwq+7GWJkzX1HguXOtdwVkblUzTw==', '{ADMIN}');