CREATE TABLE tb_notifications (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_service     VARCHAR(50)  NOT NULL,
    source_type        VARCHAR(50)  NOT NULL,
    engage_channel_id  BIGINT,
    title              VARCHAR(255) NOT NULL,
    description        TEXT,
    report             TEXT,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE tb_notification_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT       NOT NULL,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    report          TEXT,
    sequence        INTEGER      NOT NULL,

    CONSTRAINT tb_notification_items_notification_fk
        FOREIGN KEY (notification_id) REFERENCES tb_notifications ON DELETE CASCADE
);

CREATE TABLE tb_user_notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    notification_id BIGINT       NOT NULL,
    read            BOOLEAN      NOT NULL DEFAULT FALSE,
    read_at         TIMESTAMP(6) WITH TIME ZONE,
    opened_at       TIMESTAMP(6) WITH TIME ZONE,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT tb_user_notifications_user_fk
        FOREIGN KEY (user_id) REFERENCES tb_users,
    CONSTRAINT tb_user_notifications_notification_fk
        FOREIGN KEY (notification_id) REFERENCES tb_notifications ON DELETE CASCADE,
    CONSTRAINT tb_user_notifications_user_notification_uk
        UNIQUE (user_id, notification_id)
);

CREATE TABLE tb_channel_follows (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    engage_channel_id  BIGINT NOT NULL,
    created_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT tb_channel_follows_user_fk
        FOREIGN KEY (user_id) REFERENCES tb_users,
    CONSTRAINT tb_channel_follows_user_channel_uk
        UNIQUE (user_id, engage_channel_id)
);

CREATE INDEX idx_user_notifications_user_read ON tb_user_notifications (user_id, read);
CREATE INDEX idx_channel_follows_engage_channel ON tb_channel_follows (engage_channel_id);
CREATE INDEX idx_notifications_created_at ON tb_notifications (created_at DESC);
